{:user {:plugins [[lein-pedantic "0.0.5"]
                  [lein-pprint "1.1.1"]
                  [lein-midje "3.0.0"]
                  [lein-marginalia "0.7.1"]
                  [lein-release "1.0.4"]
                  [lein-vanity "0.1.0"]
                  [lein-autoreload "0.1.0"]
                  [lein-tarsier "0.10.0"]]
        :dependencies [[midje-progress-emitter "0.1.0"]]
        :vimclojure-opts {:repl true}}}
